# minimal test macro
# verbose
/run/verbose 0
/tracking/verbose 1

# apply limit to transport before run init
/QT/transport/maxtime 0.5 ns

# store trajectories in Signal ntuple
/tracking/storeTrajectory 1

# run init
/run/initialize

# max step after init
/QT/run/maxstep 0.3 mm

# set field Z value
/field/comsolFileName test.csv.gz
/field/comsolB
/field/update

# test gun
/QT/generator/test true

# start
/run/beamOn 1
