# minimal test macro
# verbose
/run/verbose 0
/tracking/verbose 2

# apply limit to transport before run init
/QT/transport/maxtime 0.5 ns
/QT/transport/maxstep 0.5 mm

# store trajectories in Signal ntuple
/tracking/storeTrajectory 1

# run init
/run/initialize

# set field Z value
/field/setFieldZ 1.0 tesla
/field/setRadius 25 mm
/field/setCurrent 100.0 ampere
/field/setZPos 20 mm
/field/bathTubB
/field/update

# test gun
/QT/generator/test true

# start
/run/beamOn 1
