# minimal test macro
# verbose
/run/verbose 0
/tracking/verbose 0

# apply limit to transport before run init
/QT/transport/maxtime 1.0 ns

# apply minimum energy before run init
/QT/transport/minenergy 10 eV

# store trajectories in Signal ntuple
/tracking/storeTrajectory 1

# run init
/run/initialize

# max step after init
/QT/run/maxstep 0.3 mm

# set field Z value
/field/setFieldZ 1.0 tesla
#/field/setField bx by bz tesla
#/field/setMinStep 0.01 mm
#/field/setRadius 20.0 mm
#/field/setCurrent 100 ampere
#/field/setZPos 20.0 mm
#/field/comsolFileName xxx.csv.gz
/field/uniformB
#/field/bathTubB
#/field/comsolB
/field/update

# test gun + all /gps commands
/QT/generator/test true
#/QT/generator/egun true
#/QT/generator/tritium true
#/QT/generator/gunEnergy 18.575
#/QT/generator/gunWidth 5.0e-4
#/QT/generator/gunSpot 0.5
#/QT/generator/order true
#/QT/generator/numass 1.0e-4
#/QT/generator/mN 0.0
#/QT/generator/eta 0.0
# example gps settings for tests
#/gps/verbose 0
#/gps/ene/mono 18.575 keV
#/gps/pos/type Volume
#/gps/pos/shape Cylinder
#/gps/pos/radius 1.5 mm
#/gps/pos/halfz 30.0 mm
#/gps/ang/type cos
#/gps/ang/mintheta 85 deg
#/gps/ang/maxtheta 89 deg

# start
/run/beamOn 1
