# minimal test macro
# verbose
/run/verbose 0
/tracking/verbose 1

# apply limit to transport before run init
/QT/transport/maxtime 0.5 ns

# store trajectories in Signal ntuple
/tracking/storeTrajectory 1

# run init
/run/initialize

# max step after init
/QT/run/maxstep 0.3 mm

# set field Z value
/field/setFieldZ 1.0 tesla
/field/setRadius 20 mm
/field/setCurrent 100.0 ampere
/field/setZPos 50 mm
/field/bathTubB
/field/update

# test gun
/QT/generator/test true

# start
/run/beamOn 1
