# minimal test macro
# verbose
/run/verbose 0
/tracking/verbose 1

# apply limit to transport before run init
/QT/transport/maxtime 0.5 ns

# store trajectories in Signal ntuple
/tracking/storeTrajectory 1

# run init
/run/initialize

# max step after init
/QT/run/maxstep 0.3 mm

# set field Z value
/field/setFieldZ 1.0 tesla
/field/uniformB
/field/update

# test GPS default, no command
/gps/verbose 2
/gps/ene/mono 18.575 keV
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 1.5 mm
/gps/pos/halfz 30.0 mm
/gps/ang/type cos
/gps/ang/mintheta 85 deg
/gps/ang/maxtheta 89 deg

# start
/run/beamOn 1
